# Generated by Django 5.2.16 on 2026-09-16 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0003_step_dates_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="step",
            options={"ordering": ["start_date", "end_date", "priority", "created_at"]},
        ),
    ]
