# Generated by Django 5.2.16 on 2026-10-09 09:30

import django.core.validators
from django.db import migrations, models
from django.db.models import Q


def delete_steps_without_coordinates(apps, schema_editor):
    Step = apps.get_model("travel", "Step")
    Step.objects.filter(Q(latitude__isnull=True) | Q(longitude__isnull=True)).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0004_alter_step_options"),
    ]

    operations = [
        migrations.RunPython(
            delete_steps_without_coordinates, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="step",
            name="latitude",
            field=models.DecimalField(
                decimal_places=7,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="longitude",
            field=models.DecimalField(
                decimal_places=7,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
    ]
