# Generated by Django 5.2.16 on 2026-10-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0005_alter_step_latitude_alter_step_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="last_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
