# Generated by Django 5.2.16 on 2026-09-09 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("travel", "0003_step_dates_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("r", "Restaurant"),
                            ("h", "Lodging"),
                            ("a", "Activity"),
                            ("s", "Sight"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("p", "Proposed"), ("c", "Chosen"), ("b", "Booked")],
                        default="p",
                        max_length=1,
                    ),
                ),
                ("localisation", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("arrival_date", models.DateTimeField(blank=True, null=True)),
                ("departure_date", models.DateTimeField(blank=True, null=True)),
                ("chosen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "chosen_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who marked the idea as chosen.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chosen_ideas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ideas",
                        to="travel.step",
                    ),
                ),
                (
                    "travel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideas",
                        to="travel.travel",
                    ),
                ),
                (
                    "traveler",
                    models.ForeignKey(
                        help_text="Who proposed the idea.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="idea.idea",
                    ),
                ),
                (
                    "traveler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="idea",
            constraint=models.CheckConstraint(
                condition=models.Q(("departure_date__gte", models.F("arrival_date"))),
                name="idea_departure_date_gte_arrival_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("traveler", "idea"), name="unique_reaction"
            ),
        ),
    ]
