# Generated by Django 5.2.16 on 2026-09-14 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idea", "0003_alter_idea_arrival_date_alter_idea_departure_date"),
        ("travel", "0003_step_dates_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="idea",
            name="idea_departure_date_gte_arrival_date",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="arrival_date",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="departure_date",
        ),
        migrations.RemoveField(
            model_name="idea",
            name="status",
        ),
        migrations.AddField(
            model_name="idea",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idea",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="idea",
            name="chosen_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who chose this lodging among the options of its step.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chosen_ideas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="idea",
            name="note",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="idea",
            name="url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="idea",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="idea_end_date_gte_start_date",
            ),
        ),
    ]
