# Generated by Django 5.2.16 on 2026-09-14 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idea", "0004_remove_idea_idea_departure_date_gte_arrival_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="price_per_night",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
