# Generated by Django 5.2.16 on 2026-10-04 11:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("idea", "0005_alter_idea_price_per_night"),
        ("travel", "0005_participation_last_read_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "body",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(2000)]
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "idea",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="idea.idea",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="travel.step",
                    ),
                ),
                (
                    "travel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="travel.travel",
                    ),
                ),
                (
                    "traveler",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who wrote the message.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["travel", "created_at"], name="message_travel_created"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_system", False),
                            ("traveler__isnull", True),
                            _connector="OR",
                        ),
                        name="message_system_has_no_author",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("step__isnull", True),
                            ("idea__isnull", True),
                            _connector="OR",
                        ),
                        name="message_step_or_idea_not_both",
                    ),
                ],
            },
        ),
    ]
