# Generated by Django 5.2.16 on 2026-10-09 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="deleted_at",
        ),
    ]
