# Generated by Django 5.2.16 on 2026-08-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traveler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="traveler",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
