# Generated by Django 5.2.16 on 2026-08-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveler', '0003_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='requested_by',
        ),
    ]
