# Generated by Django 5.2.16 on 2026-08-19 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traveler", "0004_remove_friendship_requested_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="requested_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_requested",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
