# Generated by Django 5.2.16 on 2026-08-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traveler", "0005_friendship_requested_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
