# Generated by Django 5.2.16 on 2026-09-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traveler", "0006_friendship_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traveler",
            name="profile_picture_url",
        ),
        migrations.AddField(
            model_name="traveler",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
