# Generated by Django 5.2.16 on 2026-10-01 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traveler", "0007_remove_traveler_profile_picture_url_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="friendship",
            name="unique_friendship",
        ),
        migrations.RemoveConstraint(
            model_name="friendship",
            name="friendship_sender_lt_receiver",
        ),
        migrations.RenameField(
            model_name="friendship",
            old_name="sender",
            new_name="user1",
        ),
        migrations.RenameField(
            model_name="friendship",
            old_name="receiver",
            new_name="user2",
        ),
        migrations.AlterField(
            model_name="friendship",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_requested_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(
                fields=("user1", "user2"), name="unique_friendship"
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.CheckConstraint(
                condition=models.Q(("user1__lt", models.F("user2"))),
                name="friendship_user1_lt_user2",
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("requested_by", models.F("user1")),
                    ("requested_by", models.F("user2")),
                    _connector="OR",
                ),
                name="requested_by_is_participant",
            ),
        ),
    ]
