-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 16:54:37 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Traveler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Traveler` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(80) NOT NULL,
  `LastName` VARCHAR(80) NOT NULL,
  `Username` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(80) NOT NULL,
  `ProfilePictureUrl` VARCHAR(255) NULL,
  `PasswordHash` VARCHAR(512) NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `UpdatedAt` DATETIME NOT NULL,
  `Enabled` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '0 - disabled\n1 - enabled',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TravelStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TravelStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Travel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Travel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `Paid` BOOLEAN NOT NULL DEFAULT FALSE,
  `TravelStatusId` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `UpdatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Travel_TravelStatus1_idx` (`TravelStatusId` ASC) VISIBLE,
  CONSTRAINT `fk_Travel_TravelStatus1`
    FOREIGN KEY (`TravelStatusId`)
    REFERENCES `mydb`.`TravelStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IdeaStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IdeaStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `IdeaStatuscol_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IdeaType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IdeaType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Idea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Idea` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(200) NOT NULL,
  `IdeaStatusId` INT NOT NULL,
  `Localisation` VARCHAR(255) NULL,
  `IdeaTypeId` INT NOT NULL,
  `ArrivalDate` DATETIME NOT NULL,
  `DepartureDate` DATETIME NOT NULL,
  `TravelerId` INT NOT NULL,
  `TravelId` INT NOT NULL,
  `StepId` INT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `UpdatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Idea_IdeaStatus1_idx` (`IdeaStatusId` ASC) VISIBLE,
  INDEX `fk_Idea_IdeaType1_idx` (`IdeaTypeId` ASC) VISIBLE,
  INDEX `fk_Idea_Traveler1_idx` (`TravelerId` ASC) VISIBLE,
  INDEX `fk_Idea_Travel1_idx` (`TravelId` ASC) VISIBLE,
  INDEX `fk_Idea_Step1_idx` (`StepId` ASC) VISIBLE,
  CONSTRAINT `fk_Idea_IdeaStatus1`
    FOREIGN KEY (`IdeaStatusId`)
    REFERENCES `mydb`.`IdeaStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Idea_IdeaType1`
    FOREIGN KEY (`IdeaTypeId`)
    REFERENCES `mydb`.`IdeaType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Idea_Traveler1`
    FOREIGN KEY (`TravelerId`)
    REFERENCES `mydb`.`Traveler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Idea_Travel1`
    FOREIGN KEY (`TravelId`)
    REFERENCES `mydb`.`Travel` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Idea_Step1`
    FOREIGN KEY (`StepId`)
    REFERENCES `mydb`.`Step` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Step`
-- -----------------------------------------------------
-- One row per night of the trip (end-of-day checkpoint on the
-- global timeline). A Step can be defined by a chosen Idea (e.g. an
-- accepted Idea of IdeaType 'Accommodation') via `IdeaId`, in which
-- case its location comes from that Idea's `Localisation`. If there
-- is no linked Idea, the Step stands on its own and `Localisation`
-- is set directly on the Step. `ArrivalDate` is the deadline to
-- have arrived at this Step's location that day; travel time to
-- the next Step is derived at query time from the two Steps'
-- locations rather than persisted.
CREATE TABLE IF NOT EXISTS `mydb`.`Step` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `TravelId` INT NOT NULL,
  `IdeaId` INT NULL,
  `Localisation` VARCHAR(255) NULL,
  `ArrivalDate` DATETIME NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `UpdatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Step_Travel1_idx` (`TravelId` ASC) VISIBLE,
  INDEX `fk_Step_Idea1_idx` (`IdeaId` ASC) VISIBLE,
  CONSTRAINT `fk_Step_Travel1`
    FOREIGN KEY (`TravelId`)
    REFERENCES `mydb`.`Travel` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Step_Idea1`
    FOREIGN KEY (`IdeaId`)
    REFERENCES `mydb`.`Idea` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Choice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Choice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `IdeaId` INT NOT NULL,
  `Label` VARCHAR(200) NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Choice_Idea1_idx` (`IdeaId` ASC) VISIBLE,
  CONSTRAINT `fk_Choice_Idea1`
    FOREIGN KEY (`IdeaId`)
    REFERENCES `mydb`.`Idea` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vote`
-- -----------------------------------------------------
-- One row per Traveler per Choice picked. `IdeaId` is a
-- denormalized copy of `Choice.IdeaId`, kept here only so the
-- UNIQUE constraint below can enforce "one vote per poll" at the
-- DB level. The app layer must ensure Vote.IdeaId always matches
-- the IdeaId of the Choice being voted for.
CREATE TABLE IF NOT EXISTS `mydb`.`Vote` (
  `TravelerId` INT NOT NULL,
  `ChoiceId` INT NOT NULL,
  `IdeaId` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`TravelerId`, `ChoiceId`),
  UNIQUE INDEX `one_vote_per_idea` (`TravelerId` ASC, `IdeaId` ASC) VISIBLE,
  INDEX `fk_Vote_Choice1_idx` (`ChoiceId` ASC) VISIBLE,
  INDEX `fk_Vote_Idea1_idx` (`IdeaId` ASC) VISIBLE,
  CONSTRAINT `fk_Vote_Traveler1`
    FOREIGN KEY (`TravelerId`)
    REFERENCES `mydb`.`Traveler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vote_Choice1`
    FOREIGN KEY (`ChoiceId`)
    REFERENCES `mydb`.`Choice` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vote_Idea1`
    FOREIGN KEY (`IdeaId`)
    REFERENCES `mydb`.`Idea` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TravelerRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TravelerRole` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ParticipateStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ParticipateStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participate` (
  `TravelerId` INT NOT NULL,
  `TravelId` INT NOT NULL,
  `TravelerRoleId` INT NOT NULL,
  `ParticipateStatusId` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`TravelerId`, `TravelId`),
  INDEX `fk_Traveler_has_Travel_Travel1_idx` (`TravelId` ASC) VISIBLE,
  INDEX `fk_Traveler_has_Travel_Traveler1_idx` (`TravelerId` ASC) VISIBLE,
  INDEX `fk_Participate_TravelerRole1_idx` (`TravelerRoleId` ASC) VISIBLE,
  INDEX `fk_Participate_ParticipateStatus1_idx` (`ParticipateStatusId` ASC) VISIBLE,
  CONSTRAINT `fk_Traveler_has_Travel_Traveler1`
    FOREIGN KEY (`TravelerId`)
    REFERENCES `mydb`.`Traveler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Traveler_has_Travel_Travel1`
    FOREIGN KEY (`TravelId`)
    REFERENCES `mydb`.`Travel` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participate_TravelerRole1`
    FOREIGN KEY (`TravelerRoleId`)
    REFERENCES `mydb`.`TravelerRole` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participate_ParticipateStatus1`
    FOREIGN KEY (`ParticipateStatusId`)
    REFERENCES `mydb`.`ParticipateStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Enabled` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '0 - disabled\n1 - enabled',
  `TravelId` INT NOT NULL,
  `TravelerId` INT NULL,
  `IsSystem` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '0 - regular chat message\n1 - automatic notification generated on an update',
  `Body` LONGTEXT NOT NULL,
  `SentAt` DATETIME NULL,
  `CreatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Message_Travel1_idx` (`TravelId` ASC) VISIBLE,
  INDEX `fk_Message_Traveler1_idx` (`TravelerId` ASC) VISIBLE,
  INDEX `idx_Message_Travel_CreatedAt` (`TravelId` ASC, `CreatedAt` ASC) VISIBLE,
  CONSTRAINT `fk_Message_Travel1`
    FOREIGN KEY (`TravelId`)
    REFERENCES `mydb`.`Travel` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_Traveler1`
    FOREIGN KEY (`TravelerId`)
    REFERENCES `mydb`.`Traveler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Spending`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Spending` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `EstimateCost` DECIMAL(10,2) NOT NULL,
  `RealCost` DECIMAL(10,2) NULL,
  `PaidDate` DATETIME NULL,
  `TravelerId` INT NOT NULL,
  `TravelId` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  `UpdatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Spending_Traveler1_idx` (`TravelerId` ASC) VISIBLE,
  INDEX `fk_Spending_Travel1_idx` (`TravelId` ASC) VISIBLE,
  CONSTRAINT `fk_Spending_Traveler1`
    FOREIGN KEY (`TravelerId`)
    REFERENCES `mydb`.`Traveler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Spending_Travel1`
    FOREIGN KEY (`TravelId`)
    REFERENCES `mydb`.`Travel` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
