# Generated by Django 5.2.16 on 2026-09-22 16:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("idea", "0005_alter_idea_price_per_night"),
        ("travel", "0004_alter_step_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Spending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("l", "Lodging"),
                            ("f", "Fuel"),
                            ("a", "Activities"),
                            ("m", "Meals"),
                            ("t", "Tolls"),
                            ("o", "Other"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                (
                    "idea",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spendings",
                        to="idea.idea",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spendings",
                        to="travel.step",
                    ),
                ),
                (
                    "travel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spendings",
                        to="travel.travel",
                    ),
                ),
                (
                    "traveler",
                    models.ForeignKey(
                        help_text="Who paid.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spendings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
