# Generated by Django 5.2.16 on 2026-09-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spending", "0002_alter_spending_paid_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="spending",
            name="label",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
