# Generated by Django 5.2.16 on 2026-09-29 13:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0003_spending_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('spending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='spending.spending')),
                ('traveler', models.ForeignKey(help_text='Who owes this part.', on_delete=django.db.models.deletion.PROTECT, related_name='spending_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('spending', 'traveler'), name='unique_share_per_traveler')],
            },
        ),
    ]
